# Generated by Django 2.0.7 on 2019-01-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_categories_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='cat_id',
        ),
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
