# Generated by Django 2.0.7 on 2019-01-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190112_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_ordered',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='is_paid',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
